// Generated by scripts/generate-sfx.mjs. Do not edit by hand.
/** [offsetMs, durationMs] of each sound inside /audio/sfx.wav. */
export const sfxSprite = {
  hover: [0, 45],
  click: [105, 80],
  start: [245, 490],
  boot: [795, 1150],
  transition: [2005, 620],
  glitch: [2685, 260],
  error: [3005, 320],
  secret: [3385, 925],
  on: [4370, 120],
  off: [4550, 120],
} satisfies Record<string, [number, number]>

export type SfxName = keyof typeof sfxSprite
