// Generated by https://quicktype.io

export interface AuthApiResponse {
  status: string;
  email: Email;
  message: string;
  data: Data;
}

export interface Data {
  user: User;
  token: string;
}

export interface User {
  _id: string;
  first_name: string;
  last_name: string;
  email: string;
  birthdate: Date;
  document_number: string;
  role: string;
  status: string;
  email_verified: boolean;
  is_admin: boolean;
  last_login: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface Email {
  recipient: string;
  subject: string;
  id: number;
  status: string;
  sent_at: Date;
  error_message: null;
}
