// Generated by https://quicktype.io

export interface Project {
    id:           string;
    title:        string;
    description:  string;
    technologies: string[];
    imageUrl:     string;
    demoUrl:      string;
    repoUrl:      string;
    featured:     boolean;
    createdAt:    string | Date;
    updatedAt:    string | Date;
}