// Generated by https://quicktype.io

export interface ProjectResponse {
    status:  string;
    results: number;
    data:    Datum[];
}

export interface Datum {
    id:           string;
    title:        string;
    description:  string;
    technologies: string[];
    imageUrl:     string;
    demoUrl:      string;
    repoUrl:      string;
    featured:     boolean;
    createdAt:    Date;
    updatedAt:    Date;
}
